fabrix-app/spool-cart

- README.md
- lib/config/routes.ts
- package-lock.json
- package.json
> [fix] order route prefixes

- package-lock.json
- package.json
> [chore] update dependencies

- lib/api/controllers/CustomerController.ts
- lib/api/controllers/SubscriptionController.ts
- lib/api/models/Transaction.ts
- lib/api/services/TransactionService.ts
- lib/config/routes.ts
- package-lock.json
- package.json
Adds account id to transaction for payment account transaction listings
> [feat] add account_id to transaction

- lib/api/models/Order.ts
- package-lock.json
- package.json
> [fix] transaction account_id

- lib/config/routes.ts
- package-lock.json
- package.json
> [fix] spelling error

- lib/api/analyitics/StoreAnalytic.ts
- package-lock.json
- package.json
- test/integration/3-analytics/StoreAnalytic.test.js
Adds analytics repeatCustomers, abandoned Carts
> [feat] repeatCustomers, abandoned Carts

- lib/api/analyitics/StoreAnalytic.ts
- package-lock.json
- package.json
- test/integration/2-controllers/registered/userStories/purchaseHistory.test.js
Fixes Store Analytic
- resolves noen
> [fix] analytics

- lib/api/analyitics/StoreAnalytic.ts
- lib/config/routes.ts
- package-lock.json
- package.json
Deprecate POST to subscription/:id
- resolves  none
> [feat] PUT subscription/:id

- lib/api/analyitics/StoreAnalytic.ts
- package-lock.json
- package.json
- test/fixtures/app.js
- test/integration/3-analytics/StoreAnalytic.test.js
Adds cancelled charges analytics
> [feat] cancelled charges

- lib/api/analyitics/StoreAnalytic.ts
- package-lock.json
- package.json
Fixes NR analytic
- resolves None
> [fix] NR analytics

- lib/api/controllers/SubscriptionController.ts
- package-lock.json
- package.json
- test/fixtures/app.js
- test/integration/2-controllers/admin/SubscriptionController.test.js
Fixes search subscriptions for admins
> [fix] subscription search

- lib/api/services/ProductService.ts
- package-lock.json
- test/integration/2-controllers/admin/ProductController.test.js
> attempt to fix #25

- .circleci/config.yml
- lib/api/controllers/ProductController.ts
- lib/api/policies/ProxyCartPolicy.ts
- lib/api/services/ProductService.ts
- lib/api/utils/queryDefaults/ProductVariant.ts
- lib/config/routes.ts
- package-lock.json
- package.json
- test/integration/2-controllers/admin/ProductController.test.js
> [fix] variant images

- .gitignore
- .vscode/settings.json
- lib/schemas/product/product.ts
- package-lock.json
- package.json
- test/integration/2-controllers/admin/ProductController.test.js
> update valid input for property_pricing

- lib/schemas/product/variant.ts
- test/integration/2-controllers/admin/ProductController.test.js
> [fix] correct input for property_pricing

- package-lock.json
- package.json
> [chore] correct release numbers

- lib/schemas/product/variant.ts
variant body can not take position
> add position key to variant

- lib/schemas/product/product.ts
- lib/schemas/product/variant.ts
> allow empty string/null in body

- lib/api/controllers/CollectionController.ts
- lib/api/controllers/CustomerController.ts
- lib/api/models/Collection.ts
- lib/api/services/CollectionService.ts
- lib/config/routes.ts
- package-lock.json
- package.json
- test/integration/2-controllers/admin/CollectionController.test.js
> [feat] collection analytics

- lib/api/controllers/ProductController.ts
- lib/api/services/ProductService.ts
- lib/config/routes.ts
- package-lock.json
- package.json
- test/integration/2-controllers/admin/ProductController.test.js
> [feat] product analytics

- lib/api/controllers/CollectionController.ts
- lib/api/models/Collection.ts
- lib/api/services/CollectionService.ts
- lib/api/services/CustomerService.ts
- lib/api/services/DiscountService.ts
- lib/api/services/ProductService.ts
- lib/config/routes.ts
- package-lock.json
- package.json
- test/integration/2-controllers/admin/CollectionController.test.js
- test/integration/2-controllers/admin/ProductController.test.js
- test/integration/3-analytics/StoreAnalytic.test.js
> [feat] Collection Resolver implementation

- lib/api/analyitics/StoreAnalytic.ts
- lib/api/models/Shop.ts
- package-lock.json
- package.json
- test/integration/3-analytics/StoreAnalytic.test.js
> [feat] mulit-store analytics starter

- lib/api/controllers/CustomerController.ts
- lib/api/services/CustomerService.ts
- package-lock.json
- package.json
- test/integration/2-controllers/admin/CustomerController.test.js
- Upgrades to Fabrix 1.6
- Adds the correct destroy route for a customer user, fixes add user to customer
- resolves #61
> [fix] fixes #61

- lib/api/controllers/CustomerController.ts
- lib/api/services/CustomerService.ts
- lib/config/routes.ts
- package-lock.json
- package.json
- test/integration/2-controllers/admin/CustomerController.test.js
- test/integration/2-controllers/admin/ProductController.test.js
Fix for customer's customers
- resolves #64
> [fix] Customer's Customers listing

- lib/api/controllers/CollectionController.ts
- lib/api/services/CollectionService.ts
- lib/config/routes.ts
- package-lock.json
- package.json
Collection' Collections delete endpoint
- resolves Collections point of #66
> [fix] collections endpoint of #66

- lib/api/controllers/CustomerController.ts
- lib/api/services/CustomerService.ts
- package-lock.json
- package.json
- test/integration/2-controllers/admin/CustomerController.test.js
> [fix] customer adding

- archetype/src/config/cart.ts
- lib/api/controllers/CustomerController.ts
- lib/config/routes.ts
- package-lock.json
- package.json
> [feat] customer/customer/:id

- lib/api/analyitics/StoreAnalytic.ts
- package-lock.json
- package.json
Adds defaults for auto analytics scripts
- resolves #???
> [fix] lacking analytics

- lib/api/controllers/CollectionController.ts
- lib/api/controllers/CustomerController.ts
- lib/api/controllers/ProductController.ts
- lib/api/models/Collection.ts
- package-lock.json
- package.json
- test/integration/2-controllers/admin/CollectionController.test.js
> [fix] test collections where query

- lib/api/models/Product.ts
- lib/api/models/ProductVariant.ts
- lib/api/services/ProductService.ts
- lib/api/services/ProxyCartService.ts
- package-lock.json
- package.json
- test/integration/2-controllers/admin/ProductController.test.js
> [fix] virtual calculated_price for products
